### ISSUE TITLE
added new information on alternative password for DevToolsUser account

### ISSUE THREAD

**Issue by tunip3** [xboxoneresearch/wiki#2]
https://github.com/tunip3/xboxoneresearch-wiki/tree/added-new-way-to-create-to-dev-tools-user-over-ssh

In the place of the Visual Studio pin you are able to use the smb password which can be found at /ext/smb/developerfolder on the dev portal to connect to the DevToolsUser account.
setup-dev-mode.md has been updated to reflect this

**Comment by tunip3** [comment]
its been over three months

**Comment by tuxuser** [comment]
sorry, merged

**Comment by tunip3** [comment]
thanks, sorry for being a bit passive aggressive

**Comment by tunip3** [comment]
also sorry but I just noticed a bit of an error
on line 42 of setup-dev-mode.md it should be
`For the password you are able to use either`
rather than
`For the password you are able to use either or`
