### ISSUE TITLE
Fix Markdown list parsing issues in pages ?

### ISSUE THREAD

**Issue by Randname666** [xboxoneresearch/wiki#4]
Some Lists written in markdown in the wiki (e.g. the "Notes" section in https://xosft.dev/wiki/special-ntfs-usb-files/) has not been correctly parsed by MkDocs and caused a mess. Is it possible to fix this ?

**Comment by tuxuser** [comment]
Fixed list in "Special NTFS USB files" - anything else broken?

**Comment by Randname666** [comment]
Currently no other broken lists found yet.

**Comment by tuxuser** [comment]
thanks!
