### ISSUE TITLE
xvnc.sys on xbox one system32 drivers folder

### ISSUE THREAD

**Issue by PurpleVoidEpic** [xboxoneresearch/wiki#56]
is this a xvnc because I did some research and you maybe might be able to do win32 rendering idk if this is the case but this seems interesting too look into

**Comment by PurpleVoidEpic** [comment]
I also found rdpserverbase.dll in  M:\windows\system32

**Comment by lllsondowlll** [comment]
Hello @PurpleVoidEpic ,

We would like to reserve issues for the wiki source itself. If you would like to further discuss your findings, or have questions about the Xbox feel free to join us over on the Xbox Research Matrix channel

Support or Contact
You can reach out to us on [Matrix Chat](https://matrix.to/#/#xboxoneresearch:matrix.org)
