### ISSUE TITLE
I'm having problems with xbox os version

### ISSUE THREAD

**Issue by buster95** [xboxoneresearch/wiki#72]
my internal storage got damaged so I had to change it, but I can't install offline udpates I realize It happens because OSU1 file version doesn't match with version I had installed in my xbox one which is 10.0.25398.3491 was released past month Feb/2024

anyone knows where can I find lastest os version?

**Comment by tuxuser** [comment]
This issue tracker is not really suited for (unofficial) Xbox support.

Visit us in matrix chat https://matrix.to/#/#xboxoneresearch_space:matrix.org
