### ISSUE TITLE
Looking for informations

### ISSUE THREAD

**Issue by ArKam** [xboxoneresearch/wiki#89]
Hi team, I don't know if the issue tracker is the right place to contact you about this topic, but I can't find any mailing list/discord so here I am!

I'm currently looking for a way to use the XBox one X Hardware as a base for a linux desktop, however, to do that I would need few in deep informations about the security in place and mainly, the SPBL ROM.

Does anyone know where it is located? On board? On disk? On APU (Educated guess told me it is on APU as SP seems to be on SoC)?

Do you know if, during the boot process, the AMD APU is doing anything security (fingerprinting/secureboot/etc.) related before loading the SPBL, like measurement and fingerprinting maybe?

Did someone already succeeded to extract the ROM (seems to be really hard if located within the APU) ?

Thanks a lot.

**Comment by tuxuser** [comment]
Hey,

best to join our matrix chat and we can work on getting that info updated on the wiki.

Link: https://matrix.to/#/#xboxoneresearch_space:matrix.org

thx
